pytorch_segmentation/urls.py
from django.urls import path
from pytorch_segmentation import views

app_name = 'pytorch_segmentation'
urlpatterns = [
    path('', views.index, name='index'),
    path('analysis/clean_up/', views.clean_model_analyses, name='analyses_clean_up'),
    path('analysis/comparison/', views.model_comparison, name='model_comparison'),
    path('analyses/export/', views.export, name='export'),
    path('analysis/trained_model_overview/', views.trained_model_overview, name='trained_model_overview'),
    path('analysis/trained_model/<str:analysis_pk>/', views.trained_model_analysis, name='trained_model_analysis'),
    path('analysis/trained_model/delete/<str:analysis_pk>/', views.delete_model_analysis, name='delete_model_analysis'),
    path('analysis/trained_model_import/', views.trained_model_import, name='trained_model_import'),
    path('augmentation/', views.augmentation, name='augmentation'),
    path('augmentation/image/', views.image_augmentation, name='image_augmentation'),
    path('augmentation/volume/', views.volume_augmentation, name='volume_augmentation'),
    path('datasets/', views.datasets_overview, name='datasets_overview'),
    path('datasets/delete/<str:dataset_pk>/', views.delete_dataset, name='delete_dataset'),
    path('datasets/<str:dataset_pk>/', views.edit_dataset, name='edit_dataset'),
    path('inference/', views.inference, name='inference'),
    path('logs/', views.logs, name='logs'),
    path('monitor/<str:log_pk>/', views.monitor, name='monitor'),
    path('configs/', views.configurations_overview, name='configurations_overview'),
    path(
        'configs/train/delete/<str:configuration_pk>/',
        views.delete_training_configuration,
        name='delete_training_configuration'
    ),
    path(
        'configs/inference/delete/<str:configuration_pk>/',
        views.delete_inference_configuration,
        name='delete_inference_configuration'
    ),
    path(
        'configs/train/<str:configuration_pk>/',
        views.edit_training_configuration,
        name='edit_training_configuration'
    ),
    path(
        'configs/inference/<str:configuration_pk>/',
        views.edit_inference_configuration,
        name='edit_inference_configuration'
    ),
    path('training/', views.overview, name='training_overview'),
    path('training/new_training/', views.new_training, name='new_training'),
    path('training/continuing/', views.continuing, name='continuing'),
    path('training/online_augmentation/image/', views.online_image_aug, name='online_image_aug'),
    path('training/online_augmentation/volume/', views.online_volume_aug, name='online_volume_aug'),
    path('training/online_augmentation/examples/', views.online_aug_examples, name='online_aug_examples'),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from django.urls import path

urlpatterns = [
    path('', include('pytorch_segmentation.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pytorch_segmentation/models/datasets.py
from django.db import models


class TrainingDataset(models.Model):
    name = models.CharField(
        verbose_name='Dataset Name',
        max_length=100,
        unique=True,
    )
    folder_name_on_device = models.CharField(
        verbose_name='Folder name on device',
        max_length=100,
        blank=True,
        null=True,
        unique=True,
    )
    number_training_images = models.PositiveIntegerField(
        verbose_name='Number of training images/volumes',
    )
    number_validation_images = models.PositiveIntegerField(
        verbose_name='Number of validation images/volumes',
    )

pytorch_segmentation/forms/dataset.py
import os

from django import forms

from pytorch_segmentation import constants
from pytorch_segmentation.file_handling.utils import get_sub_folders
from pytorch_segmentation.models import TrainingDataset


class TrainingDatasetForm(forms.ModelForm):
    folder_choice = forms.ChoiceField(
        label='Dataset folders on this PC',
        choices=([]),
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'}),
        help_text='Select a folder located inside "../segmentation_datasets/xx".',
    )

    class Meta:
        model = TrainingDataset
        fields = [
            'name',
            'folder_choice',
            'number_training_images',
            'number_validation_images',
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'number_training_images': forms.NumberInput(attrs={'class': 'form-control'}),
            'number_validation_images': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        dataset_choices = []
        self.deleted_choice = '__deleted__'
        dataset_folders = sorted(get_sub_folders(constants.DATASET_FOLDER, depth=1))
        for folder in dataset_folders:
            sub_folders = get_sub_folders(folder, depth=1)
            sub_folders = [os.path.basename(sub_folder) for sub_folder in sub_folders]
            if 'images' in sub_folders and 'masks' in sub_folders:
                dataset_choices.append((os.path.basename(folder), os.path.basename(folder)))

        dataset_choice_keys = [dataset_choice[0] for dataset_choice in dataset_choices]
        if self.instance and self.instance.pk is not None:
            if self.instance.folder_name_on_device and self.instance.folder_name_on_device not in dataset_choice_keys:
                dataset_choices.append((
                    f'__deleted__',
                    f'{self.instance.folder_name_on_device} (not on this pc)'
                ))

        dataset_choices.insert(0, constants.EMPTY_CHOICE)

        for field in self.fields:
            if field == 'folder_choice':
                self.fields[field].choices = dataset_choices

                if self.instance and self.instance.pk is not None:
                    if self.instance.folder_name_on_device in dataset_choice_keys:
                        self.fields[field].initial = self.instance.folder_name_on_device
                    else:
                        self.fields[field].initial = '__deleted__'

            if field in ['number_training_images', 'number_validation_images']:
                self.fields[field].help_text = self.fields[field].help_text + ' Set to 0 if unknown.'
                if self.instance and self.instance.pk is None:
                    self.fields[field].initial = 0

            if field == 'name':
                self.fields[field].help_text = 'This is the readable name to be displayed. Choose a dataset-folder ' \
                                               'from the dropdown below if one exists (only if a dataset exists, the ' \
                                               'model can be tested).'

    def clean(self):
        fcd = super(TrainingDatasetForm, self).clean()
        if fcd['folder_choice'] and 'folder_choice' in self.changed_data:
            datasets = TrainingDataset.objects.filter(folder_name_on_device=fcd['folder_choice'])
            if datasets.count() > 0:
                self.add_error('folder_choice', 'A dataset related to this folder does already exist!')
    
    def save(self, commit=True):
        initial_folder = self.instance.folder_name_on_device
        training_dataset = super().save(commit=False)
        if training_dataset.folder_name_on_device == self.deleted_choice:
            training_dataset.folder_name_on_device = initial_folder

        if 'folder_choice' in self.cleaned_data and self.cleaned_data['folder_choice'] != self.deleted_choice:
            training_dataset.folder_name_on_device = self.cleaned_data['folder_choice']

        if commit:
            training_dataset.save()
        
        return training_dataset

pytorch_segmentation/forms/export.py
from django import forms

from pytorch_segmentation.models import TrainingDataset


class ExportForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ExportForm, self).__init__(*args, **kwargs)

        datasets = TrainingDataset.objects.all()
        for dataset in datasets:
            self.fields[f'dataset_{dataset.pk}'] = forms.BooleanField(
                label=f'{dataset.name}',
                required=False,
                initial=False,
                widget=forms.CheckboxInput(attrs={'class': 'form-check-input', 'role': 'switch'}),
            )

pytorch_segmentation/forms/inference.py
import os

from django import forms

from pytorch_segmentation import constants
from pytorch_segmentation.file_handling.utils import get_file_paths_in_folder
from pytorch_segmentation.models import InferenceParameters


class InferenceInputForm(forms.ModelForm):
    class Meta:
        model = InferenceParameters
        fields = [
            'model_path',
            'data_folder',
            'device',
            'save_color',
            'log_thresh',
            'overlap',
            'weighting_strategy',
        ]
        widgets = {
            'model_path': forms.TextInput(attrs={'class': 'form-control'}),
            'data_folder': forms.TextInput(attrs={'class': 'form-control'}),

            'device': forms.Select(attrs={'class': 'form-control'}),
            'save_color': forms.CheckboxInput(attrs={'class': 'form-check-input', 'role': 'switch'}),

            'log_thresh': forms.NumberInput(attrs={'class': 'form-control'}),
            'overlap': forms.NumberInput(attrs={'class': 'form-control', 'unit': '%'}),

            'weighting_strategy': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        required_fields = [
            'model_path',
            'data_folder',
            'log_thresh',
            'overlap',
            'weighting_strategy',
        ]

        for field in self.fields:
            if field in required_fields:
                self.fields[field].required = True

    def clean(self):
        fcd = super().clean()

        if not os.path.isfile(fcd['model_path']):
            self.add_error('model_path', 'The model path does not exist.')
        elif not fcd['model_path'].endswith('.pt'):
            self.add_error('model_path', 'The model must be a .pt file.')

        if not os.path.isdir(fcd['data_folder']):
            self.add_error('data_folder', 'There is no such directory.')
        if not get_file_paths_in_folder(fcd['data_folder'], extension=constants.SUPPORTED_INPUT_IMAGE_TYPES):
            self.add_error(
                'data_folder',
                f'There is no data to segment. Supported file types are: '
                f'{", ".join(constants.SUPPORTED_INPUT_IMAGE_TYPES)}.'
            )

pytorch_segmentation/forms/optimal_configuration.py
from django import forms

from pytorch_segmentation import constants
from pytorch_segmentation.models import TrainingConfiguration, InferenceConfiguration


class InferenceConfigurationForm(forms.ModelForm):

    class Meta:
        model = InferenceConfiguration
        fields = [
            'input_height',
            'input_depth',
            'batch_size',
            'approximated_ram_usage',
        ]
        widgets = {
            'approximated_ram_usage': forms.NumberInput(attrs={'class': 'form-control'}),
            'input_height': forms.NumberInput(attrs={'class': 'form-control'}),
            'input_depth': forms.NumberInput(attrs={'class': 'form-control'}),
            'batch_size': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance and self.instance.pk is not None:
            if self.instance.architecture in constants.TWO_D_NETWORKS:
                self.fields['input_depth'].disabled = True
                self.fields['input_depth'].required = False

    def save(self, commit=True):
        optimal_configuration = super().save(commit=False)

        if 'input_height' in self.cleaned_data and self.cleaned_data['input_height']:
            optimal_configuration.input_width = self.cleaned_data['input_height']

        if commit:
            optimal_configuration.save()

        return optimal_configuration


class OptimalConfigurationForm(forms.ModelForm):

    class Meta:
        model = TrainingConfiguration
        fields = [
            'input_height',
            'input_depth',
            'batch_size',
            'approximated_ram_usage',
        ]
        widgets = {
            'approximated_ram_usage': forms.NumberInput(attrs={'class': 'form-control'}),
            'input_height': forms.NumberInput(attrs={'class': 'form-control'}),
            'input_depth': forms.NumberInput(attrs={'class': 'form-control'}),
            'batch_size': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance and self.instance.pk is not None:
            if self.instance.architecture in constants.TWO_D_NETWORKS or self.instance.fixed_depth:
                self.fields['input_depth'].disabled = True
                self.fields['input_depth'].required = False

    def save(self, commit=True):
        optimal_configuration = super().save(commit=False)

        if 'input_height' in self.cleaned_data and self.cleaned_data['input_height']:
            optimal_configuration.input_width = self.cleaned_data['input_height']

        if commit:
            optimal_configuration.save()

        return optimal_configuration

pytorch_segmentation/views/configs.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect

from pytorch_segmentation.forms import TrainingConfigurationForm, InferenceConfigurationForm
from pytorch_segmentation.models import TrainingConfiguration, InferenceConfiguration


def delete(request, config_class, config_pk):
    if isinstance(config_class, InferenceConfiguration):
        conf_type = 'inference'
    else:
        conf_type = 'training'
    try:
        configuration = config_class.objects.get(pk=config_pk)
    except ObjectDoesNotExist:
        messages.add_message(request, messages.WARNING, f'The {conf_type} configuration does not exist.')
        return redirect('pytorch_segmentation:configurations_overview')

    configuration.delete()
    messages.add_message(request, messages.SUCCESS, f'The {conf_type}  configuration was deleted.')

    return redirect('pytorch_segmentation:configurations_overview')


def edit(request, config_class, config_pk):
    if isinstance(config_class, InferenceConfiguration):
        conf_type = 'inference'
        form_class = InferenceConfigurationForm
    else:
        conf_type = 'training'
        form_class = TrainingConfigurationForm
    try:
        configuration = config_class.objects.get(pk=config_pk)
    except ObjectDoesNotExist:
        messages.add_message(request, messages.WARNING, f'The {conf_type} configuration does not exist')
        return redirect('pytorch_segmentation:configurations_overview')

    form = form_class(instance=configuration)

    if request.method == 'POST':
        form = form_class(request.POST, instance=configuration)

        if form.is_valid():
            if form.has_changed():
                form.save()
                messages.add_message(request, messages.SUCCESS, f'Saved {conf_type} configuration')

            return redirect('pytorch_segmentation:configurations_overview')

    context = {
        'form': form,
        'configuration': configuration,
        'is_training_config': True if conf_type == 'training' else False,
        'navbar_view': 'configurations',
    }
    return render(request, 'pytorch_segmentation/configuration/configuration_edit.html', context)


def edit_training_configuration(request, configuration_pk):
    return edit(request, TrainingConfiguration, configuration_pk)


def delete_training_configuration(request, configuration_pk):
    return delete(request, TrainingConfiguration, configuration_pk)


def edit_inference_configuration(request, configuration_pk):
    return edit(request, InferenceConfiguration, configuration_pk)


def delete_inference_configuration(request, configuration_pk):
    return delete(request, InferenceConfiguration, configuration_pk)


def configurations_overview(request):
    optimal_training_configurations = TrainingConfiguration.objects.order_by('architecture', 'backbone')
    optimal_inference_configurations = InferenceConfiguration.objects.order_by('architecture', 'backbone')

    context = {
        'training_configurations': optimal_training_configurations,
        'inference_configurations': optimal_inference_configurations,
        'navbar_view': 'configurations',
    }
    return render(request, 'pytorch_segmentation/configuration/configurations.html', context)

pytorch_segmentation/templates/pytorch_segmentation/analysis/analyses_clean_up.html
{% extends "pytorch_segmentation/base.html" %}
{% load static i18n dictionary list%}

{% block content_block %}

<form class="form-base-coloring" id="input_form" method="post" style="width: 100%">
    {% csrf_token %}
    <div class="centered-div">
        <p class="h3">Clean model analyses</p>
        <small>
            Here you can sanitize multiple model analyses of the database. If an analysis does not contain any data, it wil be removed.<br>
            Further, if you killed a training proces, some data might not be stored correctly.
            This will fill missing entries.
        </small>
        {% for form_field in form %}
            {# -------- #}
            {# Sub rows #}
            {# -------- #}

            {% if form_field.name|is_in_string_list:'remove_with_less_epochs_than' %}
                <div class="row em1">
            {% endif %}


            {# ------------- #}
            {# Fields #}
            {# ------------- #}

            <div class="col-sm">
                {% include '_form_field_simple.html' with field=form_field errors=form.errors field_beside_label='1' beside_label_size='col-2' beside_label_min_w='16em' field_col_size='col-1' min_width='6em' %}
            </div>

            {# --------------- #}
            {# Sub row closing #}
            {# --------------- #}

            {% if form_field.name|is_in_string_list:'remove_with_less_epochs_than' %}
                </div>
            {% endif %}

        {% endfor %}

        <div class='row'>
            <div class="col mb-1 d-flex justify-content-end">
                <button class="btn btn-danger-form"
                        style="width: 50%;"
                        type="submit">
                    Sanitize
                </button>
            </div>
        </div>
    </div>

</form>

{% endblock content_block %}

pytorch_segmentation/templates/pytorch_segmentation/analysis/model_comparison.html
{% extends "pytorch_segmentation/base.html" %}
{% load static i18n dictionary %}

{% block header %}
<link rel="stylesheet" href="{% static 'pytorch_segmentation/css/utils.css' %}">
<!-- load highcharts and annotations -->
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/annotations.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
{% endblock header %}

{% block content_block %}

<div class="comparison-hz-scroll-menu" style="width: 100%;">
    {% for id_unit_text in hz_navbar_ids_unit_text %}
        <button type="button"
                class="btn btn-primary-form {% if forloop.first %}active{% endif %}"
                id="{{ id_unit_text.0 }}"
                data-data_unit="{{ id_unit_text.1 }}">
            {{ id_unit_text.2 }}
        </button>
    {% endfor %}
</div>

<div class="row em1">

    <div class="col-10">
        <div id="js-comparison-chart" style="width:100%; height:80vh; min-height: 600px;"></div>
    </div>

    <div class="col-2">

        <div class="comparison-vt-scroll-menu" style="height: 15vh; min-height: 100px;">
            <div class="side-by-side-wrapper">
                <div class="div-left-50-percent">
                    <button type="button"
                            class="btn btn-primary-form"
                            style="width: 100%;"
                            id="js-show-2D"
                            {% if not vertical_architecture_buttons %}disabled{% endif %}>
                        Only 2D
                    </button>
                </div>
                <div class="div-right">
                    <button type="button"
                            class="btn btn-primary-form"
                            style="width: 100%;"
                            id="js-show-3D"
                            {% if not vertical_architecture_buttons %}disabled{% endif %}>
                        Only 3D
                    </button>
                </div>
            </div>

            <div class="side-by-side-wrapper">
                <div class="div-left-50-percent">
                    <button type="button"
                            class="btn btn-primary-form"
                            style="width: 100%;"
                            id="js-show-all"
                            {% if not vertical_architecture_buttons %}disabled{% endif %}>
                        Show all
                    </button>
                </div>
                <div class="div-right">
                    <button type="button"
                            class="btn btn-primary-form active"
                            style="width: 100%;"
                            id="js-hide-all"
                            {% if not vertical_architecture_buttons %}disabled{% endif %}>
                        Hide all
                    </button>
                </div>
            </div>
            <div class="side-by-side-wrapper">
                <div class="div-left-50-percent">
                    <button class="btn btn-primary-form text-end"
                            style="width: 100%;"
                            id="js-top-x"
                            disabled>
                        Only top:
                    </button>
                </div>
                <div class="div-right">
                    <div class="form needs-validation" id="best-x-form" novalidate>
                        <div class="form-group">
                            <input class="form-control"
                                   id="js-top-x-input"
                                   data-max_value="{{ vertical_architecture_buttons|length }}"
                                   type="number"
                                   readonly
                                   placeholder="1 to {{ vertical_architecture_buttons|length }}"
                                   required>
                        </div>
                    </div>
                </div>
            </div>
            {% if vertical_architecture_buttons %}
                {% for dataset_name, dataset_identifier, dataset_filter_id in dataset_filter_buttons %}
                    {% if forloop.counter0|divisibleby:2 and not forloop.last %}
                        <div class="side-by-side-wrapper">
                        <div class="div-left-50-percent">
                    {% elif not forloop.counter0|divisibleby:2 %}
                        <div class="div-right">
                    {% endif %}
                        <div class="d-flex">
                            <button type="button"
                                    class="btn btn-primary-form btn-sm"
                                    style="width: 100%; margin-top: 0.1em"
                                    data-dataset_identifier="{{ dataset_identifier }}"
                                    data-dataset_filter_button="true"
                                    id="{{ dataset_filter_id }}">
                                <small>Only {{ dataset_name }}</small>
                            </button>
                        </div>
                    {% if forloop.counter0|divisibleby:2 and not forloop.last  %}
                        </div>
                    {% elif not forloop.counter0|divisibleby:2 %}
                        </div>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>

        <div class="architecturesScrollbar dropdown_search_div" style="margin-top: 1vh;">
            {% if vertical_architecture_buttons %}
                <div id="parent_{{ architecture_id }}" class="dropdown_search_content">
                    <input type="text"
                           class="dropdown_search_input js-dropdown-filter-input"
                           data-parent_div_id="parent_{{ architecture_id }}"
                           placeholder="Search..  click one to activate"
                           style="height: 3vh; min-height: 30px;">
                    <div class="default-vt-scroll-menu" style="height: 60vh; min-height: 450px;">
                        {% for architecture_id, dom_element_properties in vertical_architecture_buttons.items %}
                            <a class="nav-link-a"
                               href="#"
                               id="{{ architecture_id }}"
                               data-dimension="{{ dom_element_properties|get_item:'dimension' }}"
                               {% for dataset_identifier in dom_element_properties|get_item:'dataset_filters' %}
                                   data-dataset_filter_{{ dataset_identifier }}="true"
                               {% endfor %}>
                                {{ dom_element_properties|get_item:'label' }}
                            </a>
                        {% endfor %}
                        <a class="nav-link-a em2"
                           href="{% url 'pytorch_segmentation:trained_model_overview' %}"
                           disabled>
                            Missing some models? Set custom names at the analysis view to enable identification.
                        </a>
                    </div>
                </div>

            {% else %}
                <button type="button"
                        class="btn btn-primary-form"
                        style="width: 100%;"
                        disabled>
                    No models stored
                </button>
            {% endif %}

        </div>

    </div>
</div>

<div class="comparison-hz-scroll-menu" style="width: 100%; margin-top: 0.1em">
    {% for dataset_name, dataset_identifier, dataset_sorting_id in dataset_sorting_buttons %}
        <button type="button"
                class="btn btn-primary-form"
                data-dataset_identifier="{{ dataset_identifier }}"
                id="{{ dataset_sorting_id }}">
            Sort by: {{ dataset_name }}
        </button>
    {% endfor %}
</div>

{% endblock content_block %}

{% block additional_scripts %}
    <p class="js-data-holder"
       data-data_dict="{{ data_dict }}"
       data-hz_navbar_ids="{{ hz_navbar_ids }}"
       data-vt_navbar_ids="{{ vt_navbar_ids }}">
    </p>
    <script src="{% static 'pytorch_segmentation/js/model_comparison.js' %}"></script>
    <script src="{% static 'pytorch_segmentation/js/dropdown_search.js' %}"></script>
{% endblock additional_scripts %}

pytorch_segmentation/templates/pytorch_segmentation/analysis/model_overview.html
{% extends "pytorch_segmentation/base.html" %}
{% load static i18n dictionary %}

{% block content_block %}

<div class="em1-left opacity-90">
    <div class="row em1">
        <div class="col-2" style="min-width: 400px;">
            <a class="btn btn-primary"
               role="button"
               style="width: 100%;"
               href="{% url 'pytorch_segmentation:analyses_clean_up' %}">
                Analyses cleaning-up view
            </a>
        </div>
        <div class="col-2" style="min-width: 400px;">
            <a class="btn btn-primary"
               role="button"
               style="width: 100%;"
               href="{% url 'pytorch_segmentation:export' %}">
                Export
            </a>
        </div>
    </div>
    <div class="row d-flex">
        {% for dataset_context in datasets_and_models %}
            <div class="col-2 em1" style="min-width: 400px;">
                <h5 class="text-color-gray">{{ dataset_context|get_item:'name' }}</h5>
                <div class="dropdown_search_div">
                    <div id="{{ dataset_context|get_item:'identifier' }}" class="dropdown_search_content show">
                        <input type="text" class="dropdown_search_input js-dropdown-filter-input" data-parent_div_id="{{ dataset_context|get_item:'identifier' }}" placeholder="Search..">
                        <div class="default-vt-scroll-menu" style="max-height: 50vh; min-height: 10vh;">
                            {% for analysis in dataset_context|get_item:'models' %}
                                <a class="nav-link-a" href="{% url 'pytorch_segmentation:trained_model_analysis' analysis.pk %}">
                                {% if not analysis.custom_name %}
                                    {{ analysis.architecture }}{% if analysis.backbone %} ({{ analysis.backbone }}){% endif %} ({{ analysis.created_datetime|date:"d.m.y" }})
                                {% else %}
                                    {{ analysis.custom_name }} ({{ analysis.created_datetime|date:"d.m.y" }})
                                {% endif %}
                                </a>
                            {% endfor %}
                        </div>
                    </div>

                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content_block %}

{% block additional_scripts %}
    <script src="{% static 'pytorch_segmentation/js/dropdown_search.js' %}"></script>
{% endblock additional_scripts %}