pytorch_segmentation/urls.py
from django.urls import path
from pytorch_segmentation import views

app_name = 'pytorch_segmentation'
urlpatterns = [
    path('', views.index, name='index'),
    path('analysis/clean_up/', views.clean_model_analyses, name='analyses_clean_up'),
    path('analysis/comparison/', views.model_comparison, name='model_comparison'),
    path('analyses/export/', views.export, name='export'),
    path('analysis/trained_model_overview/', views.trained_model_overview, name='trained_model_overview'),
    path('analysis/trained_model/<str:analysis_pk>/', views.trained_model_analysis, name='trained_model_analysis'),
    path('analysis/trained_model/delete/<str:analysis_pk>/', views.delete_model_analysis, name='delete_model_analysis'),
    path('analysis/trained_model_import/', views.trained_model_import, name='trained_model_import'),
    path('augmentation/', views.augmentation, name='augmentation'),
    path('augmentation/image/', views.image_augmentation, name='image_augmentation'),
    path('augmentation/volume/', views.volume_augmentation, name='volume_augmentation'),
    path('datasets/', views.datasets_overview, name='datasets_overview'),
    path('datasets/delete/<str:dataset_pk>/', views.delete_dataset, name='delete_dataset'),
    path('datasets/<str:dataset_pk>/', views.edit_dataset, name='edit_dataset'),
    path('inference/', views.inference, name='inference'),
    path('logs/', views.logs, name='logs'),
    path('monitor/<str:log_pk>/', views.monitor, name='monitor'),
    path('configs/', views.configurations_overview, name='configurations_overview'),
    path(
        'configs/train/delete/<str:configuration_pk>/',
        views.delete_training_configuration,
        name='delete_training_configuration'
    ),
    path(
        'configs/inference/delete/<str:configuration_pk>/',
        views.delete_inference_configuration,
        name='delete_inference_configuration'
    ),
    path(
        'configs/train/<str:configuration_pk>/',
        views.edit_training_configuration,
        name='edit_training_configuration'
    ),
    path(
        'configs/inference/<str:configuration_pk>/',
        views.edit_inference_configuration,
        name='edit_inference_configuration'
    ),
    path('training/', views.overview, name='training_overview'),
    path('training/new_training/', views.new_training, name='new_training'),
    path('training/continuing/', views.continuing, name='continuing'),
    path('training/online_augmentation/image/', views.online_image_aug, name='online_image_aug'),
    path('training/online_augmentation/volume/', views.online_volume_aug, name='online_volume_aug'),
    path('training/online_augmentation/examples/', views.online_aug_examples, name='online_aug_examples'),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from django.urls import path

urlpatterns = [
    path('', include('pytorch_segmentation.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pytorch_segmentation/models/datasets.py
from django.db import models


class TrainingDataset(models.Model):
    name = models.CharField(
        verbose_name='Dataset Name',
        max_length=100,
        unique=True,
    )
    folder_name_on_device = models.CharField(
        verbose_name='Folder name on device',
        max_length=100,
        blank=True,
        null=True,
        unique=True,
    )
    number_training_images = models.PositiveIntegerField(
        verbose_name='Number of training images/volumes',
    )
    number_validation_images = models.PositiveIntegerField(
        verbose_name='Number of validation images/volumes',
    )

pytorch_segmentation/forms/dataset.py
import os

from django import forms

from pytorch_segmentation import constants
from pytorch_segmentation.file_handling.utils import get_sub_folders
from pytorch_segmentation.models import TrainingDataset


class TrainingDatasetForm(forms.ModelForm):
    folder_choice = forms.ChoiceField(
        label='Dataset folders on this PC',
        choices=([]),
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'}),
        help_text='Select a folder located inside "../segmentation_datasets/xx".',
    )

    class Meta:
        model = TrainingDataset
        fields = [
            'name',
            'folder_choice',
            'number_training_images',
            'number_validation_images',
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'number_training_images': forms.NumberInput(attrs={'class': 'form-control'}),
            'number_validation_images': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        dataset_choices = []
        self.deleted_choice = '__deleted__'
        dataset_folders = sorted(get_sub_folders(constants.DATASET_FOLDER, depth=1))
        for folder in dataset_folders:
            sub_folders = get_sub_folders(folder, depth=1)
            sub_folders = [os.path.basename(sub_folder) for sub_folder in sub_folders]
            if 'images' in sub_folders and 'masks' in sub_folders:
                dataset_choices.append((os.path.basename(folder), os.path.basename(folder)))

        dataset_choice_keys = [dataset_choice[0] for dataset_choice in dataset_choices]
        if self.instance and self.instance.pk is not None:
            if self.instance.folder_name_on_device and self.instance.folder_name_on_device not in dataset_choice_keys:
                dataset_choices.append((
                    f'__deleted__',
                    f'{self.instance.folder_name_on_device} (not on this pc)'
                ))

        dataset_choices.insert(0, constants.EMPTY_CHOICE)

        for field in self.fields:
            if field == 'folder_choice':
                self.fields[field].choices = dataset_choices

                if self.instance and self.instance.pk is not None:
                    if self.instance.folder_name_on_device in dataset_choice_keys:
                        self.fields[field].initial = self.instance.folder_name_on_device
                    else:
                        self.fields[field].initial = '__deleted__'

            if field in ['number_training_images', 'number_validation_images']:
                self.fields[field].help_text = self.fields[field].help_text + ' Set to 0 if unknown.'
                if self.instance and self.instance.pk is None:
                    self.fields[field].initial = 0

            if field == 'name':
                self.fields[field].help_text = 'This is the readable name to be displayed. Choose a dataset-folder ' \
                                               'from the dropdown below if one exists (only if a dataset exists, the ' \
                                               'model can be tested).'

    def clean(self):
        fcd = super(TrainingDatasetForm, self).clean()
        if fcd['folder_choice'] and 'folder_choice' in self.changed_data:
            datasets = TrainingDataset.objects.filter(folder_name_on_device=fcd['folder_choice'])
            if datasets.count() > 0:
                self.add_error('folder_choice', 'A dataset related to this folder does already exist!')
    
    def save(self, commit=True):
        initial_folder = self.instance.folder_name_on_device
        training_dataset = super().save(commit=False)
        if training_dataset.folder_name_on_device == self.deleted_choice:
            training_dataset.folder_name_on_device = initial_folder

        if 'folder_choice' in self.cleaned_data and self.cleaned_data['folder_choice'] != self.deleted_choice:
            training_dataset.folder_name_on_device = self.cleaned_data['folder_choice']

        if commit:
            training_dataset.save()
        
        return training_dataset

pytorch_segmentation/forms/export.py
from django import forms

from pytorch_segmentation.models import TrainingDataset


class ExportForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ExportForm, self).__init__(*args, **kwargs)

        datasets = TrainingDataset.objects.all()
        for dataset in datasets:
            self.fields[f'dataset_{dataset.pk}'] = forms.BooleanField(
                label=f'{dataset.name}',
                required=False,
                initial=False,
                widget=forms.CheckboxInput(attrs={'class': 'form-check-input', 'role': 'switch'}),
            )

pytorch_segmentation/forms/inference.py
import os

from django import forms

from pytorch_segmentation import constants
from pytorch_segmentation.file_handling.utils import get_file_paths_in_folder
from pytorch_segmentation.models import InferenceParameters


class InferenceInputForm(forms.ModelForm):
    class Meta:
        model = InferenceParameters
        fields = [
            'model_path',
            'data_folder',
            'device',
            'save_color',
            'log_thresh',
            'overlap',
            'weighting_strategy',
        ]
        widgets = {
            'model_path': forms.TextInput(attrs={'class': 'form-control'}),
            'data_folder': forms.TextInput(attrs={'class': 'form-control'}),

            'device': forms.Select(attrs={'class': 'form-control'}),
            'save_color': forms.CheckboxInput(attrs={'class': 'form-check-input', 'role': 'switch'}),

            'log_thresh': forms.NumberInput(attrs={'class': 'form-control'}),
            'overlap': forms.NumberInput(attrs={'class': 'form-control', 'unit': '%'}),

            'weighting_strategy': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        required_fields = [
            'model_path',
            'data_folder',
            'log_thresh',
            'overlap',
            'weighting_strategy',
        ]

        for field in self.fields:
            if field in required_fields:
                self.fields[field].required = True

    def clean(self):
        fcd = super().clean()

        if not os.path.isfile(fcd['model_path']):
            self.add_error('model_path', 'The model path does not exist.')
        elif not fcd['model_path'].endswith('.pt'):
            self.add_error('model_path', 'The model must be a .pt file.')

        if not os.path.isdir(fcd['data_folder']):
            self.add_error('data_folder', 'There is no such directory.')
        if not get_file_paths_in_folder(fcd['data_folder'], extension=constants.SUPPORTED_INPUT_IMAGE_TYPES):
            self.add_error(
                'data_folder',
                f'There is no data to segment. Supported file types are: '
                f'{", ".join(constants.SUPPORTED_INPUT_IMAGE_TYPES)}.'
            )

pytorch_segmentation/forms/optimal_configuration.py
from django import forms

from pytorch_segmentation import constants
from pytorch_segmentation.models import TrainingConfiguration, InferenceConfiguration


class InferenceConfigurationForm(forms.ModelForm):

    class Meta:
        model = InferenceConfiguration
        fields = [
            'input_height',
            'input_depth',
            'batch_size',
            'approximated_ram_usage',
        ]
        widgets = {
            'approximated_ram_usage': forms.NumberInput(attrs={'class': 'form-control'}),
            'input_height': forms.NumberInput(attrs={'class': 'form-control'}),
            'input_depth': forms.NumberInput(attrs={'class': 'form-control'}),
            'batch_size': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance and self.instance.pk is not None:
            if self.instance.architecture in constants.TWO_D_NETWORKS:
                self.fields['input_depth'].disabled = True
                self.fields['input_depth'].required = False

    def save(self, commit=True):
        optimal_configuration = super().save(commit=False)

        if 'input_height' in self.cleaned_data and self.cleaned_data['input_height']:
            optimal_configuration.input_width = self.cleaned_data['input_height']

        if commit:
            optimal_configuration.save()

        return optimal_configuration


class OptimalConfigurationForm(forms.ModelForm):

    class Meta:
        model = TrainingConfiguration
        fields = [
            'input_height',
            'input_depth',
            'batch_size',
            'approximated_ram_usage',
        ]
        widgets = {
            'approximated_ram_usage': forms.NumberInput(attrs={'class': 'form-control'}),
            'input_height': forms.NumberInput(attrs={'class': 'form-control'}),
            'input_depth': forms.NumberInput(attrs={'class': 'form-control'}),
            'batch_size': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance and self.instance.pk is not None:
            if self.instance.architecture in constants.TWO_D_NETWORKS or self.instance.fixed_depth:
                self.fields['input_depth'].disabled = True
                self.fields['input_depth'].required = False

    def save(self, commit=True):
        optimal_configuration = super().save(commit=False)

        if 'input_height' in self.cleaned_data and self.cleaned_data['input_height']:
            optimal_configuration.input_width = self.cleaned_data['input_height']

        if commit:
            optimal_configuration.save()

        return optimal_configuration

pytorch_segmentation/views/configs.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect

from pytorch_segmentation.forms import TrainingConfigurationForm, InferenceConfigurationForm
from pytorch_segmentation.models import TrainingConfiguration, InferenceConfiguration


def delete(request, config_class, config_pk):
    if isinstance(config_class, InferenceConfiguration):
        conf_type = 'inference'
    else:
        conf_type = 'training'
    try:
        configuration = config_class.objects.get(pk=config_pk)
    except ObjectDoesNotExist:
        messages.add_message(request, messages.WARNING, f'The {conf_type} configuration does not exist.')
        return redirect('pytorch_segmentation:configurations_overview')

    configuration.delete()
    messages.add_message(request, messages.SUCCESS, f'The {conf_type}  configuration was deleted.')

    return redirect('pytorch_segmentation:configurations_overview')


def edit(request, config_class, config_pk):
    if isinstance(config_class, InferenceConfiguration):
        conf_type = 'inference'
        form_class = InferenceConfigurationForm
    else:
        conf_type = 'training'
        form_class = TrainingConfigurationForm
    try:
        configuration = config_class.objects.get(pk=config_pk)
    except ObjectDoesNotExist:
        messages.add_message(request, messages.WARNING, f'The {conf_type} configuration does not exist')
        return redirect('pytorch_segmentation:configurations_overview')

    form = form_class(instance=configuration)

    if request.method == 'POST':
        form = form_class(request.POST, instance=configuration)

        if form.is_valid():
            if form.has_changed():
                form.save()
                messages.add_message(request, messages.SUCCESS, f'Saved {conf_type} configuration')

            return redirect('pytorch_segmentation:configurations_overview')

    context = {
        'form': form,
        'configuration': configuration,
        'is_training_config': True if conf_type == 'training' else False,
        'navbar_view': 'configurations',
    }
    return render(request, 'pytorch_segmentation/configuration/configuration_edit.html', context)


def edit_training_configuration(request, configuration_pk):
    return edit(request, TrainingConfiguration, configuration_pk)


def delete_training_configuration(request, configuration_pk):
    return delete(request, TrainingConfiguration, configuration_pk)


def edit_inference_configuration(request, configuration_pk):
    return edit(request, InferenceConfiguration, configuration_pk)


def delete_inference_configuration(request, configuration_pk):
    return delete(request, InferenceConfiguration, configuration_pk)


def configurations_overview(request):
    optimal_training_configurations = TrainingConfiguration.objects.order_by('architecture', 'backbone')
    optimal_inference_configurations = InferenceConfiguration.objects.order_by('architecture', 'backbone')

    context = {
        'training_configurations': optimal_training_configurations,
        'inference_configurations': optimal_inference_configurations,
        'navbar_view': 'configurations',
    }
    return render(request, 'pytorch_segmentation/configuration/configurations.html', context)

pytorch_segmentation/templates/pytorch_segmentation/augmentation/augmentation.html
{% extends "pytorch_segmentation/base.html" %}
{% load static i18n dictionary %}

{% block content_block %}

<div class="container align-items-center em5">
    <div class="row em2">
        <div class="col">
            <a role="button" class="btn btn-primary btn-lg rounded-pill" href="{% url 'pytorch_segmentation:image_augmentation' %}" style="font-size: 200%; min-width: 75%;">
                Image Augmentation
            </a>
        </div>
        <div class="col">
            <a role="button" class="btn btn-primary btn-lg rounded-pill" href="{% url 'pytorch_segmentation:volume_augmentation' %}" style="font-size: 200%; min-width: 75%;">
                Volume Augmentation
            </a>
        </div>
    </div>
</div>

{% endblock content_block %}

pytorch_segmentation/templates/pytorch_segmentation/augmentation/online_aug_examples.html
{% extends "pytorch_segmentation/base.html" %}
{% load static i18n dictionary list modulo %}

{% block content_block %}

<form class="form-base-coloring" id="input_form" method="post" style="width: 100%">
    {% csrf_token %}
    <div class="centered-div">
        <p style="font-size: 125%; font-weight: 500;">Here you can create online augmentation examples.</p>
        {% for form_field in form %}
            {# -------- #}
            {# Sub rows #}
            {# -------- #}

            {% if form_field.name|is_in_string_list:'number_of_samples;' %}
                <div class="row em1">
            {% endif %}


            {# ------------- #}
            {# Fields #}
            {# ------------- #}

            <div class="col-sm">
                {% include '_form_field_simple.html' with field=form_field errors=form.errors field_beside_label='1' beside_label_size='col-2' beside_label_min_w='5em' field_col_size='col-3' min_width='11em' %}
            </div>

            {# --------------- #}
            {# Sub row closing #}
            {# --------------- #}

            {% if form_field.name|is_in_string_list:'random;' %}
                </div>
            {% endif %}

        {% endfor %}

        <div class='row justify-content-center em1'>
            {% if delete_active %}
                <div class="col">
                    <button id="js-run-kill-button" name="delete_all" class="btn btn-danger-form" style="width:100%;" type="submit">
                        Delete created examples
                    </button>
                </div>
            {% endif %}
            <div class="col mb-1">
                <button id="js-run-button" class="btn btn-success-form" style="width:100%;" type="submit" {% if process_is_running %} disabled {% endif %}>
                    Run
                </button>
            </div>
            <div class="col-1">
                {% if is_3d %}
                    <a role="button" class="btn btn-primary-form" href="{% url 'pytorch_segmentation:online_volume_aug' %}" style="width: 100%;">
                        Back
                    </a>
                {% else %}
                    <a role="button" class="btn btn-primary-form" href="{% url 'pytorch_segmentation:online_image_aug' %}" style="width: 100%;">
                        Back
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</form>
{% if examples_2d %}
    <div class="background-color-gray-dark-2">
        <div class="centered-div text-color-gray-light">
            <p style="font-size: 125%; font-weight: 500;">Examples:</p>
            <small>
                Left to right: original image and mask | augmented image and mask patch<br>
                Size of patch = network input size. Augmented image and mask passed to the network
            </small>
            {% for example in examples_2d %}
                {% if forloop.counter0|modulo:2 == 0 or forloop.first %}
                    <div class="row em1">
                {% endif %}
                    <div class="col-3">
                        <div style="height: 300px;">
                            <img src="{{ example.image.url }}" alt="image" style="max-width: 100%; max-height: 300px;">
                        </div>
                        <div style="height: 300px;">
                            <img class="em1" src="{{ example.mask.url }}" alt="mask" style="max-width: 100%; max-height: 300px;">
                        </div>
                    </div>
                    <div class="col-3">
                        <div>
                            <img src="{{ example.out_image.url }}" alt="out_image" style="max-width: 100%; max-height: 300px;">
                        </div>
                        <div>
                            <img class="em1" src="{{ example.out_mask.url }}" alt="out_mask" style="max-width: 100%; max-height: 300px;">
                        </div>
                    </div>

                {% if forloop.counter0|modulo:2 != 0 or forloop.last %}
                    </div>
                    <hr class="hz-line-gray">
                {% endif %}
            {% endfor %}
        </div>
    </div>

{% endif %}

{% endblock content_block %}

pytorch_segmentation/templates/pytorch_segmentation/augmentation/online_aug_image.html
{% extends "pytorch_segmentation/base.html" %}
{% load static i18n dictionary list%}

{% block content_block %}

<form class="form-base-coloring" id="input_form" method="post" style="width: 100%">
    {% csrf_token %}
    <div class="centered-div">
        <p style="font-size: 125%; font-weight: 500;">I need <a class="form-a " href="https://gitlab.com/fra-wa/pytorch_segmentation#tutorial">Help</a></p>
        {% for form_field in form %}
        
            {# -------- #}
            {# Sub rows #}
            {# -------- #}

            {% if form_field.name|is_in_string_list:'policy;global_strength;max_rot_angle;resizing_scale_upper;resizing_scale_lower;rotate_by_angle_prob;tilt_prob;grid_distortion_prob;grid_shuffle_prob;brightness_prob;gaussian_noise_prob;color_to_hsv_prob;random_rain_prob;random_sun_flair_prob;to_gray_prob' %}
                <div class="row em1">
            {% endif %}

            {% if form_field.name|is_in_string_list:'policy' %}
                <div class="form-group justify-content-left col-2" style="min-width: 13em;">
                    <div class="form-label-style">
                        {{form_field.label_tag}}
                    </div>
                    <div class="col-5" style="min-width: 9em;">
                        {{ form_field }}
                    </div>
                    {# ------ #}
                    {# Errors #}
                    {# ------ #}

                    {% for key, value in errors.items %}
                        {% if key == form_field.name %}
                            {% for error in errors|get_item:key %}
                                <div class="alert alert-danger" role="alert">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="col-6">
                    {% if form_field.help_text %}
                        <small class="form-text text-muted form-help-color">{{ form_field.help_text|safe }}</small>
                    {% endif %}
                </div>
                <div class="col justify-content-center" style="min-width: 30em; max-width: 50em;">
                    <button class="btn btn-primary-form" name="sample_creation_submit" style="width:100%;" type="submit">
                        Show examples
                    </button>
                    <small class="form-text text-muted form-help-color">
                        Create examples with the current augmentation settings.
                    </small>
                    <div class="row em1">
                        <div class="col">
                            <button id="js-run-button" class="btn btn-success-form" style="width:100%;" type="submit" {% if process_is_running %} disabled {% endif %}>
                                Run
                            </button>
                        </div>
                        <div class="col-2">
                            <a role="button" class="btn btn-primary-form" href="{% url 'pytorch_segmentation:new_training' %}" style="width: 100%;">
                                Back
                            </a>
                        </div>
                    </div>
                </div>
            {% else %}


                {# ------ #}
                {# Fields #}
                {# ------ #}

                <div class="col-sm">
                    {% if not form_field.name|is_in_string_list:'policy;global_strength;online_aug_start_epoch;max_augmentations' %}
                        {% include '_form_field_simple.html' with field=form_field errors=form.errors field_beside_label='1' beside_label_size='col-8' beside_label_min_w='15em' field_col_size='col-3' min_width='9em' %}
                    {% else %}
                        {% include '_form_field_simple.html' with field=form_field errors=form.errors field_col_size='col-3' min_width='9em' %}
                    {% endif %}
                </div>
            {% endif %}

            {# --------------------- #}
            {# add extra placeholder #}
            {# --------------------- #}

            {% if form_field.name|is_in_string_list:'to_sepia_prob;vertical_flip_allowed' %}
                <div class="col"></div>
            {% endif %}

            {# -------------------- #}
            {# add two placeholders #}
            {# -------------------- #}
            {% if form_field.name|is_in_string_list:'grid_shuffle_prob' %}
                <div class="col"></div>
                <div class="col"></div>
            {% endif %}

            {# --------------- #}
            {# Sub row closing #}
            {# --------------- #}

            {% if form_field.name|is_in_string_list:'policy;max_augmentations;vertical_flip_allowed;tilting_start_factor;tilting_end_factor;squeeze_prob;elastic_distortion_prob;random_crop_prob;grid_shuffle_prob;gaussian_filter_prob;channel_shuffle_prob;random_fog_prob;random_snow_prob;solarize_prob;to_sepia_prob' %}
                </div>
            {% endif %}
            {% if form_field.name|is_in_string_list:'max_augmentations;tilting_end_factor;grid_shuffle_prob' %}
                <hr class="hz-line-gray">
                {% if form_field.name == 'max_augmentations' %}
                    <p style="font-size: 125%; font-weight: 500;">General settings of some operations</p>
                {% elif form_field.name == 'tilting_end_factor' %}
                    <p style="font-size: 125%; font-weight: 500;">Geometric operations</p>
                {% elif form_field.name == 'grid_shuffle_prob' %}
                    <p style="font-size: 125%; font-weight: 500;">Radiometric operations</p>
                {% endif %}
            {% endif %}

        {% endfor %}

        <div class='row justify-content-center em1'>
            <div class="col mb-1">
                <button id="js-run-button" class="btn btn-success-form" style="width:100%;" type="submit" {% if process_is_running %} disabled {% endif %}>
                    Run
                </button>
            </div>

            {% if process_is_running %}
                <div class="col">
                    <button id="js-run-kill-button" class="btn btn-danger-form" style="width:100%;" type="submit">
                        I read the warning. Run
                    </button>
                </div>
            {% endif %}
        </div>
    </div>
</form>

{% endblock content_block %}