pytorch_segmentation/urls.py
from django.urls import path
from pytorch_segmentation import views

app_name = 'pytorch_segmentation'
urlpatterns = [
    path('', views.index, name='index'),
    path('analysis/clean_up/', views.clean_model_analyses, name='analyses_clean_up'),
    path('analysis/comparison/', views.model_comparison, name='model_comparison'),
    path('analyses/export/', views.export, name='export'),
    path('analysis/trained_model_overview/', views.trained_model_overview, name='trained_model_overview'),
    path('analysis/trained_model/<str:analysis_pk>/', views.trained_model_analysis, name='trained_model_analysis'),
    path('analysis/trained_model/delete/<str:analysis_pk>/', views.delete_model_analysis, name='delete_model_analysis'),
    path('analysis/trained_model_import/', views.trained_model_import, name='trained_model_import'),
    path('augmentation/', views.augmentation, name='augmentation'),
    path('augmentation/image/', views.image_augmentation, name='image_augmentation'),
    path('augmentation/volume/', views.volume_augmentation, name='volume_augmentation'),
    path('datasets/', views.datasets_overview, name='datasets_overview'),
    path('datasets/delete/<str:dataset_pk>/', views.delete_dataset, name='delete_dataset'),
    path('datasets/<str:dataset_pk>/', views.edit_dataset, name='edit_dataset'),
    path('inference/', views.inference, name='inference'),
    path('logs/', views.logs, name='logs'),
    path('monitor/<str:log_pk>/', views.monitor, name='monitor'),
    path('configs/', views.configurations_overview, name='configurations_overview'),
    path(
        'configs/train/delete/<str:configuration_pk>/',
        views.delete_training_configuration,
        name='delete_training_configuration'
    ),
    path(
        'configs/inference/delete/<str:configuration_pk>/',
        views.delete_inference_configuration,
        name='delete_inference_configuration'
    ),
    path(
        'configs/train/<str:configuration_pk>/',
        views.edit_training_configuration,
        name='edit_training_configuration'
    ),
    path(
        'configs/inference/<str:configuration_pk>/',
        views.edit_inference_configuration,
        name='edit_inference_configuration'
    ),
    path('training/', views.overview, name='training_overview'),
    path('training/new_training/', views.new_training, name='new_training'),
    path('training/continuing/', views.continuing, name='continuing'),
    path('training/online_augmentation/image/', views.online_image_aug, name='online_image_aug'),
    path('training/online_augmentation/volume/', views.online_volume_aug, name='online_volume_aug'),
    path('training/online_augmentation/examples/', views.online_aug_examples, name='online_aug_examples'),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from django.urls import path

urlpatterns = [
    path('', include('pytorch_segmentation.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pytorch_segmentation/models/datasets.py
from django.db import models


class TrainingDataset(models.Model):
    name = models.CharField(
        verbose_name='Dataset Name',
        max_length=100,
        unique=True,
    )
    folder_name_on_device = models.CharField(
        verbose_name='Folder name on device',
        max_length=100,
        blank=True,
        null=True,
        unique=True,
    )
    number_training_images = models.PositiveIntegerField(
        verbose_name='Number of training images/volumes',
    )
    number_validation_images = models.PositiveIntegerField(
        verbose_name='Number of validation images/volumes',
    )

pytorch_segmentation/forms/dataset.py
import os

from django import forms

from pytorch_segmentation import constants
from pytorch_segmentation.file_handling.utils import get_sub_folders
from pytorch_segmentation.models import TrainingDataset


class TrainingDatasetForm(forms.ModelForm):
    folder_choice = forms.ChoiceField(
        label='Dataset folders on this PC',
        choices=([]),
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'}),
        help_text='Select a folder located inside "../segmentation_datasets/xx".',
    )

    class Meta:
        model = TrainingDataset
        fields = [
            'name',
            'folder_choice',
            'number_training_images',
            'number_validation_images',
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'number_training_images': forms.NumberInput(attrs={'class': 'form-control'}),
            'number_validation_images': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        dataset_choices = []
        self.deleted_choice = '__deleted__'
        dataset_folders = sorted(get_sub_folders(constants.DATASET_FOLDER, depth=1))
        for folder in dataset_folders:
            sub_folders = get_sub_folders(folder, depth=1)
            sub_folders = [os.path.basename(sub_folder) for sub_folder in sub_folders]
            if 'images' in sub_folders and 'masks' in sub_folders:
                dataset_choices.append((os.path.basename(folder), os.path.basename(folder)))

        dataset_choice_keys = [dataset_choice[0] for dataset_choice in dataset_choices]
        if self.instance and self.instance.pk is not None:
            if self.instance.folder_name_on_device and self.instance.folder_name_on_device not in dataset_choice_keys:
                dataset_choices.append((
                    f'__deleted__',
                    f'{self.instance.folder_name_on_device} (not on this pc)'
                ))

        dataset_choices.insert(0, constants.EMPTY_CHOICE)

        for field in self.fields:
            if field == 'folder_choice':
                self.fields[field].choices = dataset_choices

                if self.instance and self.instance.pk is not None:
                    if self.instance.folder_name_on_device in dataset_choice_keys:
                        self.fields[field].initial = self.instance.folder_name_on_device
                    else:
                        self.fields[field].initial = '__deleted__'

            if field in ['number_training_images', 'number_validation_images']:
                self.fields[field].help_text = self.fields[field].help_text + ' Set to 0 if unknown.'
                if self.instance and self.instance.pk is None:
                    self.fields[field].initial = 0

            if field == 'name':
                self.fields[field].help_text = 'This is the readable name to be displayed. Choose a dataset-folder ' \
                                               'from the dropdown below if one exists (only if a dataset exists, the ' \
                                               'model can be tested).'

    def clean(self):
        fcd = super(TrainingDatasetForm, self).clean()
        if fcd['folder_choice'] and 'folder_choice' in self.changed_data:
            datasets = TrainingDataset.objects.filter(folder_name_on_device=fcd['folder_choice'])
            if datasets.count() > 0:
                self.add_error('folder_choice', 'A dataset related to this folder does already exist!')
    
    def save(self, commit=True):
        initial_folder = self.instance.folder_name_on_device
        training_dataset = super().save(commit=False)
        if training_dataset.folder_name_on_device == self.deleted_choice:
            training_dataset.folder_name_on_device = initial_folder

        if 'folder_choice' in self.cleaned_data and self.cleaned_data['folder_choice'] != self.deleted_choice:
            training_dataset.folder_name_on_device = self.cleaned_data['folder_choice']

        if commit:
            training_dataset.save()
        
        return training_dataset

pytorch_segmentation/forms/export.py
from django import forms

from pytorch_segmentation.models import TrainingDataset


class ExportForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ExportForm, self).__init__(*args, **kwargs)

        datasets = TrainingDataset.objects.all()
        for dataset in datasets:
            self.fields[f'dataset_{dataset.pk}'] = forms.BooleanField(
                label=f'{dataset.name}',
                required=False,
                initial=False,
                widget=forms.CheckboxInput(attrs={'class': 'form-check-input', 'role': 'switch'}),
            )

pytorch_segmentation/forms/inference.py
import os

from django import forms

from pytorch_segmentation import constants
from pytorch_segmentation.file_handling.utils import get_file_paths_in_folder
from pytorch_segmentation.models import InferenceParameters


class InferenceInputForm(forms.ModelForm):
    class Meta:
        model = InferenceParameters
        fields = [
            'model_path',
            'data_folder',
            'device',
            'save_color',
            'log_thresh',
            'overlap',
            'weighting_strategy',
        ]
        widgets = {
            'model_path': forms.TextInput(attrs={'class': 'form-control'}),
            'data_folder': forms.TextInput(attrs={'class': 'form-control'}),

            'device': forms.Select(attrs={'class': 'form-control'}),
            'save_color': forms.CheckboxInput(attrs={'class': 'form-check-input', 'role': 'switch'}),

            'log_thresh': forms.NumberInput(attrs={'class': 'form-control'}),
            'overlap': forms.NumberInput(attrs={'class': 'form-control', 'unit': '%'}),

            'weighting_strategy': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        required_fields = [
            'model_path',
            'data_folder',
            'log_thresh',
            'overlap',
            'weighting_strategy',
        ]

        for field in self.fields:
            if field in required_fields:
                self.fields[field].required = True

    def clean(self):
        fcd = super().clean()

        if not os.path.isfile(fcd['model_path']):
            self.add_error('model_path', 'The model path does not exist.')
        elif not fcd['model_path'].endswith('.pt'):
            self.add_error('model_path', 'The model must be a .pt file.')

        if not os.path.isdir(fcd['data_folder']):
            self.add_error('data_folder', 'There is no such directory.')
        if not get_file_paths_in_folder(fcd['data_folder'], extension=constants.SUPPORTED_INPUT_IMAGE_TYPES):
            self.add_error(
                'data_folder',
                f'There is no data to segment. Supported file types are: '
                f'{", ".join(constants.SUPPORTED_INPUT_IMAGE_TYPES)}.'
            )

pytorch_segmentation/forms/optimal_configuration.py
from django import forms

from pytorch_segmentation import constants
from pytorch_segmentation.models import TrainingConfiguration, InferenceConfiguration


class InferenceConfigurationForm(forms.ModelForm):

    class Meta:
        model = InferenceConfiguration
        fields = [
            'input_height',
            'input_depth',
            'batch_size',
            'approximated_ram_usage',
        ]
        widgets = {
            'approximated_ram_usage': forms.NumberInput(attrs={'class': 'form-control'}),
            'input_height': forms.NumberInput(attrs={'class': 'form-control'}),
            'input_depth': forms.NumberInput(attrs={'class': 'form-control'}),
            'batch_size': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance and self.instance.pk is not None:
            if self.instance.architecture in constants.TWO_D_NETWORKS:
                self.fields['input_depth'].disabled = True
                self.fields['input_depth'].required = False

    def save(self, commit=True):
        optimal_configuration = super().save(commit=False)

        if 'input_height' in self.cleaned_data and self.cleaned_data['input_height']:
            optimal_configuration.input_width = self.cleaned_data['input_height']

        if commit:
            optimal_configuration.save()

        return optimal_configuration


class OptimalConfigurationForm(forms.ModelForm):

    class Meta:
        model = TrainingConfiguration
        fields = [
            'input_height',
            'input_depth',
            'batch_size',
            'approximated_ram_usage',
        ]
        widgets = {
            'approximated_ram_usage': forms.NumberInput(attrs={'class': 'form-control'}),
            'input_height': forms.NumberInput(attrs={'class': 'form-control'}),
            'input_depth': forms.NumberInput(attrs={'class': 'form-control'}),
            'batch_size': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance and self.instance.pk is not None:
            if self.instance.architecture in constants.TWO_D_NETWORKS or self.instance.fixed_depth:
                self.fields['input_depth'].disabled = True
                self.fields['input_depth'].required = False

    def save(self, commit=True):
        optimal_configuration = super().save(commit=False)

        if 'input_height' in self.cleaned_data and self.cleaned_data['input_height']:
            optimal_configuration.input_width = self.cleaned_data['input_height']

        if commit:
            optimal_configuration.save()

        return optimal_configuration

pytorch_segmentation/views/configs.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect

from pytorch_segmentation.forms import TrainingConfigurationForm, InferenceConfigurationForm
from pytorch_segmentation.models import TrainingConfiguration, InferenceConfiguration


def delete(request, config_class, config_pk):
    if isinstance(config_class, InferenceConfiguration):
        conf_type = 'inference'
    else:
        conf_type = 'training'
    try:
        configuration = config_class.objects.get(pk=config_pk)
    except ObjectDoesNotExist:
        messages.add_message(request, messages.WARNING, f'The {conf_type} configuration does not exist.')
        return redirect('pytorch_segmentation:configurations_overview')

    configuration.delete()
    messages.add_message(request, messages.SUCCESS, f'The {conf_type}  configuration was deleted.')

    return redirect('pytorch_segmentation:configurations_overview')


def edit(request, config_class, config_pk):
    if isinstance(config_class, InferenceConfiguration):
        conf_type = 'inference'
        form_class = InferenceConfigurationForm
    else:
        conf_type = 'training'
        form_class = TrainingConfigurationForm
    try:
        configuration = config_class.objects.get(pk=config_pk)
    except ObjectDoesNotExist:
        messages.add_message(request, messages.WARNING, f'The {conf_type} configuration does not exist')
        return redirect('pytorch_segmentation:configurations_overview')

    form = form_class(instance=configuration)

    if request.method == 'POST':
        form = form_class(request.POST, instance=configuration)

        if form.is_valid():
            if form.has_changed():
                form.save()
                messages.add_message(request, messages.SUCCESS, f'Saved {conf_type} configuration')

            return redirect('pytorch_segmentation:configurations_overview')

    context = {
        'form': form,
        'configuration': configuration,
        'is_training_config': True if conf_type == 'training' else False,
        'navbar_view': 'configurations',
    }
    return render(request, 'pytorch_segmentation/configuration/configuration_edit.html', context)


def edit_training_configuration(request, configuration_pk):
    return edit(request, TrainingConfiguration, configuration_pk)


def delete_training_configuration(request, configuration_pk):
    return delete(request, TrainingConfiguration, configuration_pk)


def edit_inference_configuration(request, configuration_pk):
    return edit(request, InferenceConfiguration, configuration_pk)


def delete_inference_configuration(request, configuration_pk):
    return delete(request, InferenceConfiguration, configuration_pk)


def configurations_overview(request):
    optimal_training_configurations = TrainingConfiguration.objects.order_by('architecture', 'backbone')
    optimal_inference_configurations = InferenceConfiguration.objects.order_by('architecture', 'backbone')

    context = {
        'training_configurations': optimal_training_configurations,
        'inference_configurations': optimal_inference_configurations,
        'navbar_view': 'configurations',
    }
    return render(request, 'pytorch_segmentation/configuration/configurations.html', context)

pytorch_segmentation/templates/pytorch_segmentation/base.html
{% load static i18n %}

<!DOCTYPE html>
<html>

<head>
    <title>Pytorch Segmentation</title>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" type="text/javascript"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>

    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <link rel="icon" href="{% static 'pytorch_segmentation/images/favicon.png' %}">

    <link rel="stylesheet" href="{% static 'pytorch_segmentation/css/colors.css' %}">

    <link rel="stylesheet" href="{% static 'pytorch_segmentation/css/buttons.css' %}">
    <link rel="stylesheet" href="{% static 'pytorch_segmentation/css/custom_alerts.css' %}">
    <link rel="stylesheet" href="{% static 'pytorch_segmentation/css/custom_navbar.css' %}">
    <link rel="stylesheet" href="{% static 'pytorch_segmentation/css/div_alignment.css' %}">
    <link rel="stylesheet" href="{% static 'pytorch_segmentation/css/links.css' %}">
    <link rel="stylesheet" href="{% static 'pytorch_segmentation/css/relative_positioning.css' %}">
    <link rel="stylesheet" href="{% static 'pytorch_segmentation/css/scrollbar.css' %}">
    <link rel="stylesheet" href="{% static 'pytorch_segmentation/css/search_dropdown.css' %}">
    <link rel="stylesheet" href="{% static 'pytorch_segmentation/css/utils.css' %}">

    {% block header %}
    {% endblock header %}

</head>

<body>
    <img class="img-fluid" style="width:100vw;" src="{% static 'pytorch_segmentation/images/main_theme/navbar_simple_text_thin.png' %}" alt="theme">
    <div class="container-fluid" >
        {# ----------------- #}
        {# Navbar with image #}
        {# ----------------- #}

        <div class="side-by-side-wrapper">
            <div class="div-left-150px">
                {# --------------- #}
                {# Left navigation #}
                {# --------------- #}
                <nav class="navbar navbar-custom justify-content-start">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link {% if navbar_view == 'index' %} active {% endif %}" href="{% url 'pytorch_segmentation:index' %}">
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if navbar_view == 'training' %} active {% endif %}" href="{% url 'pytorch_segmentation:training_overview' %}">
                                Training
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if navbar_view == 'inference' %} active {% endif %}" href="{% url 'pytorch_segmentation:inference' %}">
                                Inference
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if navbar_view == 'trained_models' %} active {% endif %}" href="{% url 'pytorch_segmentation:trained_model_overview' %}">
                                Trained Models
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if navbar_view == 'model_comparison' %} active {% endif %}" href="{% url 'pytorch_segmentation:model_comparison' %}">
                                Comparison
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if navbar_view == 'augmentation' %} active {% endif %}" href="{% url 'pytorch_segmentation:augmentation' %}">
                                Augmentation
                            </a>
                        </li>
                        <li class="nav-item">
                            <p class="em1 {% if navbar_view|is_in_string_list:'model_import;datasets;logs;monitor' %} text-color-white {% else %} text-color-gray {% endif %} ">More:</p>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if navbar_view == 'model_import' %} active {% endif %}" href="{% url 'pytorch_segmentation:trained_model_import' %}">
                                Model Import
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if navbar_view == 'datasets' %} active {% endif %}" href="{% url 'pytorch_segmentation:datasets_overview' %}">
                                Datasets
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if navbar_view == 'configurations' %} active {% endif %}" href="{% url 'pytorch_segmentation:configurations_overview' %}">
                                Configurations
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if navbar_view == 'logs' %} active {% endif %}" href="{% url 'pytorch_segmentation:logs' %}">
                                Logs
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if navbar_view == 'monitor' %} active {% endif %}" href="{% url 'pytorch_segmentation:monitor' '-1' %}">
                                Monitor
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://gitlab.com/fra-wa/pytorch_segmentation/-/blob/master/README.md">
                                About
                            </a>
                        </li>
                        <li>
                            <p style="font-size: 75%; color: #84868b;">
                                Background: <a class="nav-link" href="https://wallpaperbat.com/">&#169;WallpaperBat</a>
                            </p>
                        </li>

                    </ul>

                </nav>
            </div>

            {# -------------- #}
            {# Main container #}
            {# -------------- #}
            <div class="div-right">
                <main class="container-main">
                    {% include "_messages.html" %}
                    {% block content_block %}
                    <!-- Content here -->
                    {% endblock content_block %}
                </main>
            </div>
        </div>
    </div>
    {% block additional_scripts %}

    {# ------------ #}
    {# Scripts here #}
    {# ------------ #}

    {% endblock additional_scripts %}
</body>

</html>

pytorch_segmentation/templates/pytorch_segmentation/index.html
{% extends "pytorch_segmentation/base.html" %}
{% load static i18n dictionary %}

{% block content_block %}

<div class="container align-items-center em5">
    <div class="row em2">
        <div class="col">
            <a role="button" class="btn btn-primary btn-lg rounded-pill" href="{% url 'pytorch_segmentation:training_overview'%}" style="font-size: 200%;  width: 100%;">
                Training
            </a>
        </div>
        <div class="col">
            <a role="button" class="btn btn-primary btn-lg rounded-pill" href="{% url 'pytorch_segmentation:augmentation' %}" style="font-size: 200%; width: 100%;">
                Augmentation
            </a>
        </div>
        <div class="col">
            <a role="button" class="btn btn-primary btn-lg rounded-pill" href="{% url 'pytorch_segmentation:inference' %}" style="font-size: 200%; width: 100%;">
                Inference
            </a>
        </div>
    </div>
    <div class="row em2">
         <div class="col">
            <a role="button" class="btn btn-primary btn-lg rounded-pill" href="{% url 'pytorch_segmentation:trained_model_overview' %}" style="font-size: 200%; width: 100%;">
                Trained Models
            </a>
        </div>
        <div class="col">
            <a role="button" class="btn btn-primary btn-lg rounded-pill" href="{% url 'pytorch_segmentation:model_comparison' %}" style="font-size: 200%; width: 100%;">
                Comparison
            </a>
        </div>
        <div class="col">
            <a role="button" class="btn btn-primary btn-lg rounded-pill" href="{% url 'pytorch_segmentation:trained_model_import' %}" style="font-size: 200%; width: 100%;">
                Import
            </a>
        </div>
    </div>

</div>

{% endblock content_block %}

pytorch_segmentation/templates/pytorch_segmentation/logs.html
{% extends "pytorch_segmentation/base.html" %}
{% load static i18n dictionary %}

{% block content_block %}
    <div class="row d-flex opacity-90">
        {% for log_name, log_query in logs.items %}
            {% if log_query %}
                <div class="col em1" style="min-width: 250px;">
                    <h5 class="text-color-gray background-color-gray-dark-3">{{ log_name }}</h5>
                    <div class="dropdown_search_div">
                        <div id="{{ log_name }}" class="log_dropdown_search_content show">
                            <input type="text" class="dropdown_search_input js-dropdown-filter-input" data-parent_div_id="{{ log_name }}" placeholder="Search..">
                            <div class="default-vt-scroll-menu" style="max-height: 50vh; min-height: 10vh;">
                                {% for log in log_query %}
                                    <a class="logs-a{% if log in running_logs %} active{% endif %}" href="{% url 'pytorch_segmentation:monitor' log.pk %}">
                                        {{ log.process_start_datetime|date:"l, d.m.y., G:i:s" }}{% if log in running_logs %} (running) {% endif %}
                                    </a>
                                {% endfor %}
                            </div>
                        </div>

                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock content_block %}
{% block additional_scripts %}
    <script src="{% static 'pytorch_segmentation/js/dropdown_search.js' %}"></script>
{% endblock additional_scripts %}

pytorch_segmentation/templates/pytorch_segmentation/trained_model_import.html
{% extends "pytorch_segmentation/base.html" %}
{% load static i18n dictionary list%}

{% block content_block %}

<form class="form-base-coloring" id="input_form" method="post" style="width: 100%">
    {% csrf_token %}
    <div class="centered-div">
        <p class="h3">Import networks trained with this framework</p>
        <small>If you trained a neural network on a different pc, you can import it here.</small>
        {% for form_field in form %}
            {# -------- #}
            {# Sub rows #}
            {# -------- #}

            {% if form_field.name|is_in_string_list:'checkpoint_path;search_in_sub_folders;dataset_choice' %}
                <div class="row em1">
            {% endif %}

            {# ------------- #}
            {# Fields #}
            {# ------------- #}

            <div class="col-sm">
                {% if not form_field.name|is_in_string_list:'checkpoint_path' %}
                    {% include '_form_field_simple.html' with field=form_field errors=form.errors field_beside_label='1' beside_label_size='col-4' beside_label_min_w='15em' field_col_size='col-6' min_width='18em' %}
                {% else %}
                    {% include '_form_field_simple.html' with field=form_field errors=form.errors %}
                {% endif %}
            </div>

            {# --------------- #}
            {# Sub row closing #}
            {# --------------- #}

            {% if form_field.name|is_in_string_list:'checkpoint_path;only_last_of_sub_folder;dataset_choice' %}
                {% if form_field.name == 'dataset_choice' %}
                    <div class="col-sm">
                        <a role="button" id="create_dataset" class="btn btn-primary-form" href="{% url 'pytorch_segmentation:edit_dataset' -1 %}">
                            Create new dataset
                        </a>
                    </div>
                {% endif %}
                </div>
            {% endif %}
        {% endfor %}

        <div class='row justify-content-center em1'>
            <div class="col mb-1">
                <button id="js-run-button" class="btn btn-success-form" style="width:100%;" type="submit">
                    Import
                </button>
            </div>
        </div>
    </div>

</form>

{% endblock content_block %}